//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrariWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasat
    {
        public int Id { get; set; }
        public string Klasa { get; set; }
        public Nullable<int> Kapaciteti { get; set; }
        public Nullable<int> Tipi { get; set; }
        public string Godina { get; set; }
        public Nullable<int> Kati { get; set; }
        public bool Perdoret { get; set; }
        public string KlasaNew { get; set; }
    }
}
