//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrariWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ORARI_DEMOEntities : DbContext
    {
        public ORARI_DEMOEntities()
            : base("name=ORARI_DEMOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deget> Degets { get; set; }
        public virtual DbSet<Disponibel> Disponibels { get; set; }
        public virtual DbSet<Ditet> Ditets { get; set; }
        public virtual DbSet<ImportLendet> ImportLendets { get; set; }
        public virtual DbSet<Klasat> Klasats { get; set; }
        public virtual DbSet<Lendet> Lendets { get; set; }
        public virtual DbSet<Orari> Oraris { get; set; }
        public virtual DbSet<Oret> Orets { get; set; }
        public virtual DbSet<Tipet> Tipets { get; set; }
    }
}
