//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrariWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orari
    {
        public int Id { get; set; }
        public string Dega { get; set; }
        public int Viti { get; set; }
        public string Paraleli { get; set; }
        public string Lenda { get; set; }
        public string Tipi { get; set; }
        public string Pedagog { get; set; }
        public int Dita { get; set; }
        public int Klasa { get; set; }
        public int Ora { get; set; }
        public Nullable<int> Zgjedhje { get; set; }
        public Nullable<bool> Final { get; set; }
    }
}
